# Generated by Django 4.2.1 on 2026-01-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='addoncategory',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='addon_categories', to='products.product'),
        ),
    ]
