# Generated by Django 4.2.1 on 2026-01-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_addoncategory_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='specific_products',
            field=models.ManyToManyField(blank=True, related_name='specific_addons', to='products.product'),
        ),
    ]
