# Generated by Django 4.2.1 on 2025-09-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_guest_email_order_guest_name_order_guest_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='addons_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
