# Generated by Django 4.2.1 on 2025-09-01 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_addons_snapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='addons_snapshot',
            new_name='addons',
        ),
    ]
