# Generated by Django 4.2.1 on 2025-09-01 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_product_categories'),
        ('orders', '0005_rename_addons_snapshot_orderitem_addons'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=3, help_text='Percentage (0–100) or fixed amount in KWD depending on type.', max_digits=10)),
                ('applies_to_all', models.BooleanField(default=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Max total uses across all users', null=True)),
                ('per_user_limit', models.PositiveIntegerField(blank=True, help_text='Max uses per single user', null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Leave empty if applies_to_all is true.', related_name='discount_codes', to='products.category')),
                ('products', models.ManyToManyField(blank=True, help_text='Leave empty if applies_to_all is true.', related_name='discount_codes', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='orders.discountcode')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usage', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
