# Generated by Django 4.2.1 on 2025-08-30 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('currency', models.CharField(default='KWD', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], default='initiated', max_length=16)),
                ('invoice_id', models.CharField(blank=True, max_length=64, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=64, null=True)),
                ('method_id', models.IntegerField(blank=True, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('currency', models.CharField(default='KWD', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('paid', 'Paid'), ('failed', 'Failed')], default='initiated', max_length=10)),
                ('address_id', models.IntegerField(blank=True, null=True)),
                ('cart_snapshot', models.JSONField(blank=True, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=64, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=64, null=True)),
                ('method_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_payment', to='orders.order')),
            ],
        ),
    ]
