# Generated by Django 4.2.1 on 2025-09-01 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_discount_order_discount_amount'),
        ('payments', '0003_checkoutpayment_guest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutpayment',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_payments', to='orders.discountcode'),
        ),
    ]
